// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCknZHZjPtXUIogcQvQv_xDPGU2UpWRE10',
    appId: '1:254006289444:web:0ea2726975a8881f2d64b1',
    messagingSenderId: '254006289444',
    projectId: 'chat-app-51ba8',
    authDomain: 'chat-app-51ba8.firebaseapp.com',
    storageBucket: 'chat-app-51ba8.firebasestorage.app',
    measurementId: 'G-4X839KM80M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvJagtNJCEBrJvesG1c2hllW4h6oZUZiA',
    appId: '1:254006289444:android:c31af0aa9d9ac1a42d64b1',
    messagingSenderId: '254006289444',
    projectId: 'chat-app-51ba8',
    storageBucket: 'chat-app-51ba8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAobcmpWDL9WKjGZ0xDZHlsqAY506gDSmU',
    appId: '1:254006289444:ios:64514123eafdcc9d2d64b1',
    messagingSenderId: '254006289444',
    projectId: 'chat-app-51ba8',
    storageBucket: 'chat-app-51ba8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAobcmpWDL9WKjGZ0xDZHlsqAY506gDSmU',
    appId: '1:254006289444:ios:64514123eafdcc9d2d64b1',
    messagingSenderId: '254006289444',
    projectId: 'chat-app-51ba8',
    storageBucket: 'chat-app-51ba8.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCknZHZjPtXUIogcQvQv_xDPGU2UpWRE10',
    appId: '1:254006289444:web:b9384f62819508b62d64b1',
    messagingSenderId: '254006289444',
    projectId: 'chat-app-51ba8',
    authDomain: 'chat-app-51ba8.firebaseapp.com',
    storageBucket: 'chat-app-51ba8.firebasestorage.app',
    measurementId: 'G-NH329X6YBS',
  );
}
